server:
  port: 8900
  servlet:
    context-path: /patient
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5440/patient_db"
    driverClassName: "org.postgresql.Driver"
    username: user
    password: 123456

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    patient: http://localhost:8900/patient

appointment-service:
  url: http://localhost:8901/appointment

inventory-service:
  url: http://localhost:8903/inventory
#  security:
#    user:
#      name: admin
#      password: admin