services:
  identity-postgres:
    image: postgres:17
    container_name: identity-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
    volumes:
      - identity-postgres:/var/lib/postgresql/data

  profile-postgres:
    image: postgres:17
    container_name: profile-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profile_db
    volumes:
      - profile-postgres:/var/lib/postgresql/data
  patient-postgres:
    image: postgres:17
    container_name: patient-postgres
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: patient_db
    volumes:
      - patient-postgres:/var/lib/postgresql/data
  appointment-postgres:
    image: postgres:17
    container_name: appointment-postgres
    restart: always
    ports:
      - "5441:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: appointment_db
    volumes:
      - appointment-postgres:/var/lib/postgresql/data
  inventory-postgres:
    image: postgres:17
    container_name: inventory-postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inventory_db
    volumes:
      - inventory-postgres:/var/lib/postgresql/data
  staff-mongo:
    image: mongo:6
    container_name: staff-mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: aye10diemtoan0
      MONGO_INITDB_ROOT_PASSWORD: 3YuYOFfiujAFdZEc
      MONGO_INITDB_DATABASE: staff_db
    volumes:
      - staff-mongo-data:/data/db
# Show Data on http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aye10diemtoan0
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3YuYOFfiujAFdZEc
      ME_CONFIG_MONGODB_SERVER: staff-mongo

volumes:
  identity-postgres:
  profile-postgres:
  patient-postgres:
  appointment-postgres:
  staff-mongo-data:
  inventory-postgres:
