server:
  port: 8800
  servlet:
    context-path: /staff

spring:
  data:
    mongodb:
      uri: mongodb+srv://aye10diemtoan0:3YuYOFfiujAFdZEc@cluster0.qsvbeha.mongodb.net/staff_db?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoOperations: DEBUG

app:
  services:
    staff: http://localhost:8800/staff