server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:postgresql://applyscrum-bachkhoaactive.g.aivencloud.com:26872/defaultdb"
    driverClassName: "org.postgresql.Driver"
    username: avnadmin
    password: AVNS_M3r0L2izKLsjEy29NN3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"