server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/identity_db"
    driverClassName: "org.postgresql.Driver"
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000000000
  refreshable-duration: 3600000000 # second

feignclient:
  patient-service:
    url: "http://localhost:8900/patient"
  staff-service:
    url: "http://localhost:8800/staff"
