server:
  port: 8902
  servlet:
    context-path: /hospital
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5441/hospital_db"
    driverClassName: "org.postgresql.Driver"
    username: user
    password: 123456

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    patient: http://localhost:8902/hospital


#  security:
#    user:
#      name: admin
#      password: admin