server:
  port: 8888
app:
  prefix-api: /api/v1
  prefix-num: 2
spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.prefix-api}/identity/**
          filters:
            - StripPrefix=${app.prefix-num}
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.prefix-api}/profile/users/**
          filters:
            - StripPrefix=${app.prefix-num}
        - id: patient
          uri: http://localhost:8900/patient
          predicates:
            - Path=${app.prefix-api}/patient/**
          filters:
            - StripPrefix=${app.prefix-num}